### ISSUE TITLE
local_frame_advantage bigger than i8::MAX

### ISSUE THREAD

**Issue by cscorley** [gschup/ggrs#35]
**Describe the bug**
Calculations for quality reports use i8 and can be too small during stress testing.

**To Reproduce**
- Using https://github.com/cscorley/bevy_ggrs_rapier_example
- Compile using release build
- Setup a game and introduce aggressive network lag such that 127+ "Skipping a frame: PredictionThreshold" will be produced on the clients
- Observe panic `thread 'main' panicked at 'local_frame_advantage bigger than i8::MAX: TryFromIntError(())', C:\Users\cscorley\scoop\persist\rustup\.cargo\git\checkouts\ggrs-151f8bd9eb75dc5d\9e4a20a\src\network\protocol.rs:512:18`

**Expected behavior**
Non-panic, just keep skipping frames.

**Screenshots**
I was testing a game with clumsy on Windows, using this configuration.
![image](https://user-images.githubusercontent.com/112752/171040983-babb35ea-988e-4dd3-9ae7-957716f7f218.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: main branch, 9e4a20a6317cfdcff9c352e6f2a37feb33576e54

**Additional context**

**Comment by gschup** [comment]
Thanks for your report!

While this would be easy to fix by going from i8 to i32 or comparable, I am very curious how this issue can arise. Usually, when adding advancing the gamestate without remote input, `PredictionThreshold` occurs to halt the user from advancing too much [(error is thrown here)](https://github.com/gschup/ggrs/blob/9e4a20a6317cfdcff9c352e6f2a37feb33576e54/src/sync_layer.rs#L165).

This _should_ mean that `local_frame_advantage` should never be higher than the max prediction threshold, which [by default is 8](https://github.com/gschup/ggrs/blob/9e4a20a6317cfdcff9c352e6f2a37feb33576e54/src/sessions/builder.rs#L18). In [your example](https://github.com/cscorley/bevy_ggrs_rapier_example/blob/cedfd7432f58f82106ce7f2cc3f57fda7b813263/src/main.rs#L23), you left that threshold at 8. 

At this point, I can only hypothesize, but maybe there is a slippery cast from unsigned to signed and there is a silent overflow due to going negative? I will check it out later this week, probably on or shortly before the weekend.

PS: [Sounds great!](https://github.com/cscorley/bevy_ggrs_rapier_example/blob/cedfd7432f58f82106ce7f2cc3f57fda7b813263/src/main.rs#L26)

**Comment by gschup** [comment]
Another thought: Since the clumsy settings aren't too extreme (I tested worse), could it maybe be the case that one of the clients cannot keep up with the framerate? This could especially be the case with rapier and big physics things...

**Comment by MaxCWhitehead** [comment]
I have reproduced a couple of these while stepping through a ggrs test in debugger (so there are larger delays in wall clock time). This does not play nice with the code using wall clock time in ggrs, and can cause issues.

I most commonly hit
`thread 'main' panicked at 'assertion failed: frame_to_load != NULL_FRAME && frame_to_load < self.current_frame &&\n    frame_to_load >= self.current_frame - self.max_prediction as i32',`
I believe this is due to a rollback being triggered for disconnect_frame 0 (disconnect frame chosen as first_incorrect), when current_frame is also 0. 

When debugging I commented out the time check that triggers network interrupt events, and then after that I reproduced the assert in original post. Remote frame in the local frame advantage computation is based on an estimation with ping + framerate. It does not actually use the true remote frame, so when debugging or in very poor net conditions, it is possible for this to get very large and assert.

(Not sure if it's sound for this failure to occur considering I commented out disconnect code - but just sharing notes on that.)

**Comment by MaxCWhitehead** [comment]
> You may be right about it being related to actual framerate and not network. I also have tested this by just laying down a `sleep 3s` (e.g. dumb cap to approximate 180 frames) in one of the client systems and it seems to just "break through" the PredictionThreshold (after 111 of them) and allow one client to continue rendering, all before the other even completes it's first frame. (I do not have any framerate limiting in bevy itself, just the FPS limit set by bevy_ggrs)

I would recommend confirming disconnect events are handled, I have a suspicion that may be the cause. Once client is disconnected GGRS will report this event, and continue to advance.

**Comment by caspark** [comment]
I encountered this today: while running in a browser, I switched to a different tab - and browsers do chicanery such as pausing code running in inactive tabs (or at least, I know they don't call `requestAnimationFrame()`, and perhaps macroquad is using that to drive its main loop - I haven't checked), so the assert failed for me too.

Should be easy to fix either by clamping the value to i8::MAX or bumping to a larger instead - an extra few bytes included in the quality report every 200 milliseconds to every player (if I've understood the code correctly) should be fine, I'd think.

I am not sure that it matters much exactly which approach we pick, since it's likely that if the game is paused in a debugger or suspended in a background tab then it will get disconnected by other clients imminently, but I suppose just bumping to i16 and clamping is a middle of the road approach.

So I've raised a PR to do that: https://github.com/gschup/ggrs/pull/91
